### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by pluehne** [bluec0re/android-backup-tools#3]
Hi @bluec0re, do you plan to make an initial release of this package? `android-backup-tools` already is a dependency of [`python-miio`](https://github.com/rytilahti/python-miio/), and it would be really helpful to be able to reference a specific version number as the dependency. This also concerns packaging for Linux distributions, where it’s generally required to explicitly state version numbers for packages.

No need to rush an initial release, I just wanted to bring this to your attention 🙂.

**Comment by bluec0re** [comment]
You mean on pypi? https://pypi.python.org/pypi/android_backup

**Comment by pluehne** [comment]
Ah, I hadn’t seen this before 🙂. I had looked for a release tag here on GitHub, but didn’t find one.

Maybe you could add a tag for `v0.1.0` here on GitHub, so that I can refer to this release in the AUR packages that I created for [`android-backup-tools`](https://aur.archlinux.org/packages/python-android-backup-tools-git/) and [`python-miio`](https://aur.archlinux.org/packages/python-miio/)? It’s usually preferred for distribution packages to be built from the source directly rather than from a site that redistributes the sources.

**Comment by pluehne** [comment]
@bluec0re: Thank you very much for the release tag 😃! It would be helpful if you could keep on creating Git tags for future releases 🙂.
