### ISSUE TITLE
Encrypted Backup

### ISSUE THREAD

**Issue by beleka** [bluec0re/android-backup-tools#5]
Hello everyone, i got a backup from an encrypted device. When i try to unpack it using:

python unpack.py -p "xxxxxxxxxxx" -t ~/AndroidTest/ /home/beleka/android.ab

i get the next error:

__________________________________________

Traceback (most recent call last):
  File "unpack.py", line 59, in <module>
    main()
  File "unpack.py", line 54, in main
    password=args.password
  File "/usr/local/lib/python2.7/dist-packages/android_backup/android_backup.py", line 364, in unpack
    pickle_fname = os.path.basename(fname) + '.pickle'
NameError: global name 'fname' is not defined

________________________________________

I get the same error with the command without -p modifier and with a quoted password. I hope you can help me.

**Comment by bluec0re** [comment]
Should be fixed now. Could you pull the changes and test it again?

**Comment by beleka** [comment]
Sry but the problem is hitting back once again! xD Thank you for your time but now i have another problem: 
_______________

Traceback (most recent call last):
  File "unpack.py", line 59, in <module>
    main()
  File "unpack.py", line 54, in main
    password=args.password
  File "/root/android-backup-tools-master/android_backup/android_backup.py", line 373, in unpack
    tar = self.read_data(password)
  File "/root/android-backup-tools-master/android_backup/android_backup.py", line 340, in read_data
    fp = self._decrypt(fp, password=password)
  File "/root/android-backup-tools-master/android_backup/android_backup.py", line 191, in _decrypt
    master_iv = bytes(master_key[:l])
TypeError: slice indices must be integers or None or have an __index__ method

____________________________________

I'm trying to solve it, if i can do that i post here the solution. Now without the p modifier it works propertly, but this is an encrypted device so i need it.

**Comment by bluec0re** [comment]
Hm, this is a strange one. could you test it with python 3 and/or change

```
l = master_key.pop(0)
```
to
```
l = ord(master_key.pop(0))
```
? (I'm currently unable to execute/test the code myself).

Could be an issue with pycrypto returning strings instead of bytes.

**Comment by beleka** [comment]
Hello and sorry for everything. I tested it with python3 installing pycrypto and worked perfectly. The solution with l = ord(master...) prints out a problem because the ord() function is waiting a string and not a integer. 

Thank you for everything and sry for taking your time. Great work.

**Comment by bluec0re** [comment]
No worries, thanks for using (& testing) this :)

I've enabled automated tests and fixed the python 2/3 compatibility issues.

Based on the unit tests, everything should be fine now.
